### ISSUE TITLE
[Port to OpenCL] Diffraction Patterns

### ISSUE THREAD

**Issue by AJcodes** [OpenCL/GEGL-OpenCL#13]
Port the GEGL Operation **Diffraction Patterns** to OpenCL, with optimizations targeting the following:-
- Nvidia GPU
- AMD GPU
- Intel GPU
- CPU

**Comment by VincentSC** [comment]
https://github.com/OpenCL/GEGL-OpenCL/pull/72/commits/855cc073091762cabd67ba513ca7cc1b3b13dfe1
