### ISSUE TITLE
[Port to OpenCL] Gaussian Blur Selective

### ISSUE THREAD

**Issue by AJcodes** [OpenCL/GEGL-OpenCL#19]
Port the GEGL Operation **Gaussian Blur Selective** to OpenCL, with optimizations targeting the following:-
- Nvidia GPU
- AMD GPU
- Intel GPU
- CPU

**Comment by VincentSC** [comment]
https://github.com/OpenCL/GEGL-OpenCL/pull/72/commits/f407e25046a017b635354da14bb5f010dd4c7d11
