### ISSUE TITLE
[Port to OpenCL] Motion Blur Circular

### ISSUE THREAD

**Issue by AJcodes** [OpenCL/GEGL-OpenCL#28]
Port the GEGL Operation **Motion Blur Circular** to OpenCL, with optimizations targeting the following:-
- Nvidia GPU
- AMD GPU
- Intel GPU
- CPU

**Comment by VincentSC** [comment]
https://github.com/OpenCL/GEGL-OpenCL/pull/72/commits/6546c6fd6e3adad3bdd0ff1edb37e673e6b5bc06
