### ISSUE TITLE
[Port to OpenCL] Noise HSV

### ISSUE THREAD

**Issue by AJcodes** [OpenCL/GEGL-OpenCL#31]
Port the GEGL Operation **Noise HSV** to OpenCL, with optimizations targeting the following:-
- Nvidia GPU
- AMD GPU
- Intel GPU
- CPU

**Comment by VincentSC** [comment]
https://github.com/OpenCL/GEGL-OpenCL/pull/72/commits/91379e95356222db31f536aaceb97a65aef4dfc0
